import { useState, useEffect } from "react";
import {
  CheckCircle,
  AlertCircle,
  ShieldCheck,
  Sparkles,
  TrendingUp,
  DollarSign,
  Settings,
  RefreshCw,
  XCircle,
  HelpCircle,
} from "lucide-react";
import ApprovalCard from "../components/ApprovalCard";

// Directly import the real Gemini recommendations generated by your script!
import localRecommendations from "../../reports/google_ads/gemini_recommendations.json";

export default function GoogleAds() {
  const [executiveSummary, setExecutiveSummary] = useState("");
  const [recommendations, setRecommendations] = useState([]);
  const [falsePositives, setFalsePositives] = useState([]);
  const [appliedActions, setAppliedActions] = useState([]);
  const [showSafetyPanel, setShowSafetyPanel] = useState(false);
  const [syncing, setSyncing] = useState(false);

  // Initialize state from the imported JSON
  useEffect(() => {
    if (localRecommendations) {
      setExecutiveSummary(localRecommendations.executiveSummary || "");
      setRecommendations(localRecommendations.recommendations || []);
      setFalsePositives(localRecommendations.falsePositivesSafety || []);
    }
  }, []);

  // Calculate dynamic savings based on active/unprocessed recommendations
  const activeSavingsTotal = recommendations.reduce((sum, rec) => {
    const rawVal = rec.costSavings.replace(/[^0-9.]/g, "");
    return sum + (parseFloat(rawVal) || 0);
  }, 0);

  const handleApprove = (id) => {
    const approvedRec = recommendations.find((r) => r.id === id);
    setRecommendations(recommendations.filter((r) => r.id !== id));
    setAppliedActions([
      ...appliedActions,
      {
        id,
        title: approvedRec?.title || id,
        status: "approved",
        savings: approvedRec?.costSavings || "$0.00",
        keywordsCount: approvedRec?.negativeKeywordsToApply?.length || 0,
        timestamp: new Date().toLocaleTimeString(),
      },
    ]);
  };

  const handleReject = (id) => {
    const rejectedRec = recommendations.find((r) => r.id === id);
    setRecommendations(recommendations.filter((r) => r.id !== id));
    setAppliedActions([
      ...appliedActions,
      {
        id,
        title: rejectedRec?.title || id,
        status: "rejected",
        savings: "$0.00",
        keywordsCount: 0,
        timestamp: new Date().toLocaleTimeString(),
      },
    ]);
  };

  const triggerCloudSync = () => {
    setSyncing(true);
    // Simulate push queue sync to Google Ads API
    setTimeout(() => {
      setSyncing(false);
      alert(
        "Success! Approved exclusions have been pushed securely to your Google Ads account via Cloud Functions.",
      );
    }, 1500);
  };

  return (
    <div className="space-y-8 max-w-7xl mx-auto">
      {/* Header Banner */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-200 pb-5">
        <div>
          <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight flex items-center gap-2.5">
            <Sparkles className="h-7 w-7 text-blue-600 shrink-0" />
            Google Ads Command Center
          </h1>
          <p className="text-slate-500 mt-1">
            Real-time Traffic Audit, Budget Leakage Controls, and Brand
            Protections
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={() => setShowSafetyPanel(!showSafetyPanel)}
            className="bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 px-4 py-2 rounded-lg text-sm font-semibold transition flex items-center gap-2 shadow-sm"
          >
            <ShieldCheck className="h-4 w-4 text-emerald-600" />
            {showSafetyPanel
              ? "Hide Safety Logs"
              : `View Protected Keywords (${falsePositives.length})`}
          </button>

          {appliedActions.some((a) => a.status === "approved") && (
            <button
              onClick={triggerCloudSync}
              disabled={syncing}
              className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm font-semibold transition flex items-center gap-2 shadow-sm disabled:opacity-50"
            >
              <RefreshCw
                className={`h-4 w-4 ${syncing ? "animate-spin" : ""}`}
              />
              {syncing ? "Syncing with Ads API..." : "Sync Approved Exclusions"}
            </button>
          )}
        </div>
      </div>

      {/* Account Performance Overview Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-slate-900 text-white rounded-2xl p-6 shadow-md border border-slate-800 relative overflow-hidden">
          <div className="absolute right-0 bottom-0 opacity-10">
            <AlertCircle className="h-32 w-32 -mr-4 -mb-4" />
          </div>
          <span className="text-xs text-slate-400 font-bold uppercase tracking-wider block">
            Account Diagnostics
          </span>
          <div className="flex items-center gap-2 mt-2">
            <span
              className={`h-3 w-3 rounded-full ${recommendations.length > 0 ? "bg-red-500 animate-pulse" : "bg-emerald-500"}`}
            ></span>
            <span className="text-lg font-bold text-slate-100">
              {recommendations.length > 0
                ? `${recommendations.length} Active Leaks Flagged`
                : "Account Secure & Optimized"}
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-2 leading-relaxed">
            {recommendations.length > 0
              ? "Performance Max campaign matches are driving low-intent terms. Exclusions required immediately."
              : "All active budget leakage points have been mitigated and synced."}
          </p>
        </div>

        <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm relative overflow-hidden">
          <span className="text-xs text-slate-500 font-bold uppercase tracking-wider block">
            Est. Monthly Savings Potential
          </span>
          <h2 className="text-3xl font-extrabold text-emerald-600 mt-2">
            ${activeSavingsTotal.toFixed(2)}/mo
          </h2>
          <span className="text-[11px] text-slate-400 font-medium block mt-1">
            Based on active AI recommendations
          </span>
        </div>

        <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm relative overflow-hidden">
          <span className="text-xs text-slate-500 font-bold uppercase tracking-wider block">
            False Positive Shields Active
          </span>
          <h2 className="text-3xl font-extrabold text-blue-600 mt-2">
            🛡️ {falsePositives.length}
          </h2>
          <span className="text-[11px] text-emerald-600 font-semibold flex items-center gap-0.5 mt-1">
            <CheckCircle className="h-3 w-3" /> 100% High-Intent Traffic
            Protected
          </span>
        </div>
      </div>

      {/* Executive Summary Banner */}
      {executiveSummary && recommendations.length > 0 && (
        <div className="bg-blue-50/50 border border-blue-100 rounded-2xl p-6 space-y-3">
          <h3 className="font-bold text-blue-950 text-base flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-blue-600" /> Executive Analysis by
            Gemini 2.5 Flash
          </h3>
          <p className="text-sm text-slate-700 leading-relaxed">
            {executiveSummary}
          </p>
        </div>
      )}

      {/* Recommendations & Protected keywords column splitter */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Recommendation Column */}
        <div
          className={`space-y-6 ${showSafetyPanel ? "lg:col-span-2" : "lg:col-span-3"}`}
        >
          <h2 className="text-xl font-bold text-slate-900">
            Gemini-Generated Optimizations
          </h2>

          {recommendations.length > 0 ? (
            <div
              className={`grid grid-cols-1 gap-6 ${showSafetyPanel ? "sm:grid-cols-1" : "md:grid-cols-2 lg:grid-cols-3"}`}
            >
              {recommendations.map((rec) => (
                <div
                  key={rec.id}
                  className="bg-white rounded-xl shadow-sm border border-slate-200 p-5 flex flex-col justify-between"
                >
                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <span
                        className={`text-[10px] font-bold px-2 py-0.5 rounded border uppercase ${
                          rec.impact === "high"
                            ? "bg-red-50 text-red-700 border-red-100"
                            : "bg-amber-50 text-amber-700 border-amber-100"
                        }`}
                      >
                        {rec.impact} impact
                      </span>
                      <span className="text-xs font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded">
                        {rec.costSavings}
                      </span>
                    </div>

                    <h3 className="font-extrabold text-slate-900 text-base">
                      {rec.title}
                    </h3>
                    <p className="text-xs text-slate-600 leading-relaxed">
                      {rec.desc}
                    </p>

                    {/* Excluded Keyword Tags */}
                    {rec.negativeKeywordsToApply && (
                      <div className="space-y-1.5 pt-2">
                        <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wide block">
                          Keywords to Exclude:
                        </span>
                        <div className="flex flex-wrap gap-1">
                          {rec.negativeKeywordsToApply
                            .slice(0, 10)
                            .map((kw, i) => (
                              <span
                                key={i}
                                className="bg-slate-100 text-slate-700 text-[10px] px-1.5 py-0.5 rounded border border-slate-200"
                              >
                                {kw}
                              </span>
                            ))}
                          {rec.negativeKeywordsToApply.length > 10 && (
                            <span className="bg-blue-50 text-blue-700 font-semibold text-[9px] px-1.5 py-0.5 rounded border border-blue-100">
                              +{rec.negativeKeywordsToApply.length - 10} more
                            </span>
                          )}
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="border-t border-slate-100 pt-4 mt-5 flex items-center justify-between gap-4">
                    <span className="text-[11px] text-slate-500 font-medium">
                      {rec.difficulty}
                    </span>
                    <div className="flex gap-2 shrink-0">
                      <button
                        onClick={() => handleReject(rec.id)}
                        className="px-2.5 py-1.5 border border-slate-200 rounded-lg text-xs font-semibold text-slate-600 hover:bg-slate-50"
                      >
                        Reject
                      </button>
                      <button
                        onClick={() => handleApprove(rec.id)}
                        className="px-2.5 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-xs font-semibold"
                      >
                        Approve
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-10 text-center max-w-xl mx-auto space-y-4">
              <CheckCircle className="h-12 w-12 text-emerald-600 mx-auto" />
              <h3 className="text-xl font-bold text-emerald-950">
                All recommendations processed!
              </h3>
              <p className="text-sm text-emerald-700 leading-relaxed">
                Excellent work! Your Google Ads account is locked down tight and
                operating at maximum efficiency.
              </p>
              {appliedActions.some((a) => a.status === "approved") && (
                <button
                  onClick={triggerCloudSync}
                  className="mt-4 bg-emerald-600 hover:bg-emerald-700 text-white font-semibold py-2 px-6 rounded-lg text-sm shadow transition"
                >
                  Push Approved Changes to Live Google Ads API
                </button>
              )}
            </div>
          )}
        </div>

        {/* Protected Keywords Panel (Shows when toggled) */}
        {showSafetyPanel && (
          <div className="space-y-6">
            <h2 className="text-xl font-bold text-slate-900 flex items-center gap-2">
              <ShieldCheck className="h-5 w-5 text-emerald-600 shrink-0" />
              Traffic Protections
            </h2>
            <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm space-y-4 max-h-[600px] overflow-y-auto">
              <div className="text-xs text-slate-500 leading-relaxed border-b border-slate-100 pb-3">
                Below are critical, high-intent keywords that matched your
                account traffic. Gemini explicitly recognized these as{" "}
                <strong>highly profitable</strong> for your core business and
                protected them from being accidentally blocked.
              </div>
              <div className="space-y-3">
                {falsePositives.map((item, i) => (
                  <div
                    key={i}
                    className="p-3 bg-slate-50 border border-slate-150 rounded-lg text-xs space-y-1"
                  >
                    <div className="flex items-center justify-between">
                      <strong className="text-slate-950 text-sm font-bold">
                        "{item.term}"
                      </strong>
                      <span className="text-[9px] font-bold bg-emerald-50 text-emerald-700 border border-emerald-100 px-1.5 py-0.2 rounded-full uppercase tracking-wide">
                        Protected
                      </span>
                    </div>
                    <p className="text-slate-600 leading-relaxed">
                      {item.reason}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Action History Log */}
      {appliedActions.length > 0 && (
        <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <h3 className="font-bold text-slate-900 text-sm flex items-center gap-2">
              <Settings className="h-4 w-4 text-slate-400" /> Action Queue
              History
            </h3>
            <span className="text-xs font-semibold text-slate-400">
              {appliedActions.length} actions in local buffer
            </span>
          </div>
          <ul className="divide-y divide-slate-100 text-xs">
            {appliedActions.map((action, i) => (
              <li
                key={i}
                className="py-3 flex flex-col sm:flex-row sm:items-center justify-between gap-2"
              >
                <div className="space-y-0.5">
                  <span className="text-slate-800 font-bold block">
                    {action.title}
                  </span>
                  <span className="text-slate-400 text-[10px]">
                    Action ID: {action.id} • Processed at {action.timestamp}
                  </span>
                </div>
                <div className="flex items-center gap-3">
                  {action.status === "approved" && (
                    <span className="text-[10px] font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-100 shrink-0">
                      Approved (+{action.keywordsCount} Exclusions)
                    </span>
                  )}
                  {action.status === "rejected" && (
                    <span className="text-[10px] font-bold text-slate-500 bg-slate-50 px-2 py-0.5 rounded border border-slate-100 shrink-0">
                      Rejected
                    </span>
                  )}
                  {action.savings !== "$0.00" && (
                    <strong className="text-emerald-600 font-bold shrink-0">
                      {action.savings}/mo Saved
                    </strong>
                  )}
                </div>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
